@startuml

class Bird {
  String name
  string color
  void Speak()
  void fly()
}
Bird <|-- Pigeon
class Pigeon {
void Speak()
void eatPizza()
}

Bird <|-- Penguin
class Penguin {
void Speak()
void fly()

}

@enduml